### ISSUE TITLE
国内大学发的论文应该提供中文版

### ISSUE THREAD

**Issue by taozuhong** [TsinghuaDatabaseGroup/AIDB#18]
国内大学发的论文没有中文版，这算不算是对衣食父母（纳税人）不责任的表现？
要知道国内大学花的也是纳税人的钱，发中文版是你们应有之义......

只发英文版，对中文社区和国内纳税人的贡献就大打折扣了，你们的产出就算赢得了国外的认可，可也要赢得国内衣食父母（纳税人）的认可是不？就目前来看，国内公众似乎不太认可哦：
[论清华大学的崩塌](https://zhuanlan.zhihu.com/p/628740020)
[为什么清华大学被称为汉奸摇篮](https://zhuanlan.zhihu.com/p/632302589)
[为什么清华大学总有负面新闻，挨网友骂？](https://www.zhihu.com/question/599509294/answer/3098258042)
[清华大学校长给高考考生发出邀请信，遭众人辱骂，清华怎么了？](https://zhuanlan.zhihu.com/p/637392873)

**Comment by XuanheZhou** [comment]
中文论文请在知网检索 https://kns.cnki.net/kns8/defaultresult/index

王勇,李国良,李开宇.联邦学习贡献评估综述[J].软件学报,2023,34(03):1168-1192.DOI:10.13328/j.cnki.jos.006786.

张超,李国良,冯建华等.HTAP数据库关键技术综述[J].软件学报,2023,34(02):761-785.DOI:10.13328/j.cnki.jos.006713.

孙佶,李国良.人在回路的数据融合系统[J].计算机学报,2022,45(03):654-668.

金连源,李国良.基于人工智能方法的数据库智能诊断[J].软件学报,2021,32(03):845-858.DOI:10.13328/j.cnki.jos.006177.

李国良,周煊赫,孙佶等.基于机器学习的数据库技术综述[J].计算机学报,2020,43(11):2019-2049.

**Comment by taozuhong** [comment]
可否请你把所列论文全部附上中文版链接入口？

在事实打脸的情况下，我会改变最初的判断（更新），谢谢。
