### ISSUE TITLE
Incorrect Paper Classification (Possible)

### ISSUE THREAD

**Issue by paul356** [TsinghuaDatabaseGroup/AIDB#26]
It seems this paper is not about "learned layout". It argues about Radix Join against Non-partitioned Joins. Should it be classified to "plan optimization"?

[Learned Layout] Bandle, M., Giceva, J., & Neumann, T. (2021). To Partition, or Not to Partition, That is the Join Question in a Real System. SIGMOD, 2021. [[paper](https://doi.org/10.1145/3448016.3452831)]

**Comment by XuanheZhou** [comment]
Sorry for the delayed response. It is a good issue that requires some further discussion. 

From my understanding, plan optimization is about, given the fixed physical operators and statistics like indexes, optimizing the execution plan of an input query (e.g., switching the join order or selecting the physical operator types). Thus, whether works like [radix join] should be classified into "plan optimization"? They seem to be contributions in execution level (e.g., "query execution")?

Looking forward to your follow-up opinions -:)

**Comment by paul356** [comment]
I think you are right. "Query Execution" maybe is a more suitable category than "Plan Optimization". I guess they are both better than "Learned Layout". :-P

**Comment by XuanheZhou** [comment]
Yeah, I have fixed it, and welcome more advice or even PRs!
